### ISSUE TITLE
Usage 

### ISSUE THREAD

**Issue by twisbrogan** [ManchesterIO/django-nginx-remote-user-middleware#1]
Hi,

I'm trying to set up a Nginx > Django site that uses NTLM for single sign on. Presuming that this was written to solve that issue, do you have any example configurations for it?

**Comment by cnorthwood** [comment]
Hi, it's not for NTLM no, it was just to get Sentry to integrate with our single sign on system, rather than use its own. Here's a sample nginx file if that's what you're looking for: https://github.com/ManchesterIO/manchester.io/blob/master/deploy/site-cookbooks/manchesterio/templates/default/sentry-server.erb, and the relevant Sentry/Django configuration: https://github.com/ManchesterIO/manchester.io/blob/master/deploy/site-cookbooks/manchesterio/templates/default/sentry.conf.py.erb#L64

**Comment by twisbrogan** [comment]
Thanks for the reply & links, Chris. 

So Sentry credentials were in the htpasswd file and your scripts passed them onto Django using the HTTP_REMOTE_USER variable (or something like that). I'm obviously in a different environment but hopefully, I'll reach a point where I'm able to identify something from NTLM to pass to my Django app :)

**Comment by cnorthwood** [comment]
basically yes, happy to help!
